"""Short proof-reading decisions; constructing proofs remains wholly open."""


def author(recognition):
    choices = {
        'direct-proof': {
            1: ('Assume a and b are odd integers; conclude a+b is even.', ['Assume a+b is even; conclude both inputs are odd.', 'Assume a and b are the same odd integer; conclude a+b is even.']),
            4: ('Both entries are integers, and the denominator is nonzero.', ['Both entries are real numbers, with any denominator.', 'Only the numerator must be an integer.']),
            5: ('The two odd integers may need different witnesses; one shared witness forces equality.', ['Every odd integer has the same witness.', 'Different letters are required even when the integers are known equal.']),
            7: ('Establish a solution exists, then show any two solutions are equal.', ['Show any two solutions equal; existence follows automatically.', 'Find one solution; other solutions cannot exist.']),
            9: ('An arbitrary integer has only the stated assumptions, so the argument covers every allowed integer.', ['A random sample is automatically arbitrary.', 'An arbitrary integer must be positive.']),
            10: ('An allowed domain element with true hypothesis and false conclusion.', ['Any input with a false hypothesis.', 'Any input with a false conclusion, even outside the domain.']),
            54: ('Division by zero is undefined; require a nonzero rational divisor.', ['Require a positive numerator; a zero divisor is allowed.', 'Exclude irrational numerators; rational division by zero is rational.']),
            63: ('The square root loses negative roots, and its proposed parity witness is not shown to be an integer.', ['Every nonnegative real witness proves evenness.', 'Only a missing positive sign is the problem.']),
            65: ('Add the missing case x=0, where x squared is 0.', ['Discard x=0 because it is not real.', 'The positive and negative cases already cover zero.']),
            67: ('Prove the reverse inclusion; the right set may still contain extra elements.', ['Nothing: one inclusion proves equality.', 'Prove both sets are nonempty.']),
            69: ('At most one solution; existence is still unproved.', ['Exactly one solution, because any two are equal.', 'No solutions, because distinct ones cannot exist.']),
        },
        'proof-by-contrapositive': {
            7: ('Every integer has exactly one parity; arbitrary reals need not be even or odd.', ['Every real is even or odd.', 'Only positive integers have parity.']),
            9: ('Contraposition assumes not-Q to derive not-P; contradiction assumes P and not-Q to derive impossibility.', ['Both methods begin by assuming not-P.', 'Contraposition assumes Q; contradiction assumes P.']),
            10: ('No: with P true and Q false, the inverse is true while the original is false.', ['Yes: inverse and original always have the same truth table.', 'Yes: negating both statements always preserves implication.']),
            61: ('The converse: even root implies even square.', ['The contrapositive: odd root implies odd square.', 'The original: even square implies even root.']),
            64: ('The second factor could be even; negating the conclusion requires both factors odd.', ['One odd factor always makes the product odd.', 'The second factor must also be odd whenever the first is odd.']),
            65: ('The remainder-2 case is missing; both nonzero remainders must be checked.', ['The remainder-0 case is the only missing case.', 'No case is missing because all nonmultiples have remainder 1.']),
            67: ('Require a nonzero integer denominator; its square is then nonzero too.', ['A zero denominator is allowed after squaring.', 'Only the numerator needs to be nonzero.']),
            70: ('Contraposition preserves the domain; enlarging it adds cases and may invalidate parity language.', ['Contraposition automatically changes integers into reals.', 'A larger domain always makes a statement easier to prove.']),
        },
        'proof-by-contradiction': {
            10: ('A negative number contradicts only an additional condition that rules it out.', ['Every negative number is impossible.', 'Negative numbers invalidate every algebraic proof.']),
            21: ('Integer numerator, positive denominator, and no common divisor greater than 1; flip both signs if needed.', ['A positive denominator alone establishes lowest terms.', 'Lowest terms means numerator smaller than denominator.']),
            22: ('A remaining factor h greater than 1 would give original common divisor gh greater than the greatest divisor g.', ['Dividing by any positive common divisor always produces lowest terms.', 'Reduced entries cannot have any positive common divisor, including 1.']),
            24: ('Both entries even share divisor 2, contradicting lowest terms.', ['Both entries even contradict rationality itself.', 'An even denominator is always forbidden.']),
            29: ('Substitution gives k squared equals b squared, which does not force b even; 2/1 is a representation.', ['The same pattern proves square root of 4 irrational.', 'Even a always forces even b in every rational representation.']),
            30: ('A prime dividing an integer square divides its root.', ['Every positive divisor of a square divides its root.', 'Every prime divides every square.']),
            41: ('The divisor candidates include N and lie in the finite set from 2 to N.', ['Every subset of the reals has a smallest member.', 'N must itself be prime.']),
            43: ('Composite numbers may have prime divisors; the divisor need not equal the original number.', ['Having a prime divisor makes the original number prime.', 'Composite numbers have no prime divisors.']),
            44: ('2 is prime, so the complete list is nonempty and its positive product is at least 2.', ['An empty product is zero, so adding 1 exceeds 1.', 'Any integer product plus 1 exceeds 1.']),
            50: ('It rules out only that count; the assumption must allow an arbitrary finite complete list.', ['Ruling out two primes also rules out every finite count.', 'Every finite set has exactly two members.']),
            61: ('Even entries are compatible with an unreduced fraction; first choose lowest terms.', ['Rational representations cannot have even entries.', 'The proof needs a larger denominator.']),
            62: ('The constructed number need only have a prime divisor; that divisor is absent from the complete list.', ['A product of primes plus 1 is always prime.', 'The constructed number must divide every prime on the list.']),
            63: ('The negation is P and not-Q; refuting not-P establishes only P.', ['The negation of P implies Q is not-P.', 'Assuming not-P automatically assumes not-Q.']),
            65: ('Require the rational multiplier to be nonzero; zero makes the product rational.', ['Require only that the irrational number be nonzero.', 'Division by a rational zero is permitted.']),
            66: ('A contradiction follows if the same integer is both even and odd, for example when a=b.', ['Different integers cannot have different parities.', 'Any even integer contradicts any odd integer.']),
            67: ('It assumes its own conclusion; the supporting facts must be established independently.', ['Citing the desired conclusion proves it.', 'Irrationality proofs cannot use lemmas.']),
            68: ('a-b is zero, so division by it is undefined.', ['Subtracting equal numbers is forbidden.', 'Setting a=b is itself a contradiction.']),
            70: ('It establishes at most one solution, which permits either zero or one.', ['It proves there are no solutions.', 'It proves a solution exists.']),
        },
        'mathematical-induction': {
            4: ('The step proves a conditional; the base and induction principle establish the family.', ['Assuming the next case is always allowed.', 'The base case alone proves every later case.']),
            5: ('No: forward induction from 2 covers only indices at least 2.', ['Yes: any base case covers all integer indices.', 'Yes: the inductive step always works backward.']),
            6: ('Unit steps from 0 reach integers and miss real numbers such as one half.', ['Every nonnegative real is reached by finitely many unit steps.', 'There is a next real number after every real number.']),
            8: ('The initial value and recurrence define the sequence; the closed formula is the claim to prove.', ['The closed formula is part of the given definition.', 'The recurrence may be assumed only after the formula is proved.']),
            9: ('A nonnegative factor preserves the inequality; a negative factor reverses it.', ['Every factor preserves an inequality.', 'Multiplication always reverses an inequality.']),
            10: ('A stronger hypothesis may provide extra information needed for the next step.', ['A stronger statement needs no base case.', 'A weaker statement can never be proved directly.']),
            39: ('No: a theorem starting at 4 needs only that base and later steps.', ['Yes: a failure below the base invalidates every induction.', 'No: checking the base at 4 alone is sufficient.']),
            40: ('The obtained bound must still be compared with the target (k+1) squared.', ['Every bound involving k automatically proves the next case.', 'The induction hypothesis must instead be assumed at k+1.']),
            52: ('The update for u uses v, so both formulas supply the values needed for the next step.', ['The u recurrence never depends on v.', 'Simultaneous induction eliminates the need for initial values.']),
            57: ('Every relevant operation must avoid overflow or use an adequate integer representation.', ['Machine integers always behave like unbounded mathematical integers.', 'Only the final stored value needs to avoid overflow.']),
            60: ('No: preservation proves a conditional property; termination needs a separate argument.', ['Yes: any invariant forces the loop to stop.', 'Yes: initialized variables cannot support an infinite loop.']),
            61: ('The implication does not supply a true starting case.', ['The implication guarantees every case is true.', 'A base is needed only when the step fails.']),
            62: ('Justify every transformation as reversible, or rewrite the proof forward from the hypothesis.', ['A true consequence always proves the statement it came from.', 'Assume the target without further justification.']),
            63: ('Include the needed earlier statement in a strengthened hypothesis with sufficient bases.', ['P(k) automatically includes every earlier statement.', 'Use P(k-1) freely because it has a smaller index.']),
            64: ('The transitions through 2, 3 and 4 need initial checks or separate valid steps.', ['The base at 1 automatically supplies the base at 4.', 'No extra checks are needed because the general step eventually works.']),
            65: ('The two one-horse groups have no common horse to transfer color equality.', ['The two groups always share one horse.', 'The base case of a single horse has two colors.']),
            67: ('The hypothesis says 4 to the k minus 1 is divisible by 3, not 4 to the k.', ['The hypothesis says 4 to the k itself is divisible by 3.', 'A divisibility witness may be chosen without checking the equation.']),
            68: ('At n=0 the sum contains the single term 2 to the zero, which is 1.', ['At n=0 the sum is empty and equals zero.', 'At n=0 the term is 2 times zero.']),
            69: ('Prove the step for an arbitrary allowed k; finite examples do not cover all later cases.', ['Checking five cases establishes every possible pattern.', 'Only one more numerical check is needed.']),
            70: ('Forward steps from a positive base do not reach negative indices.', ['An induction theorem automatically covers negative indices.', 'Negative indices have no mathematical meaning.']),
        },
        'strong-induction': {
            1: ('At target n, assume P(j) for every integer with 2 at most j less than n.', ['Assume P(j) for every j at most n, including the target.', 'Assume P(1) only, regardless of the theorem’s domain.']),
            2: ('Strong induction supplies every earlier case in the domain; ordinary induction supplies the preceding case.', ['Strong induction permits assuming the current target.', 'Strong induction removes all base requirements.']),
            3: ('Ordinary induction on the conjunction of all cases through n supplies the strong hypothesis.', ['Strong induction can prove claims that ordinary induction cannot.', 'Ordinary induction has no need for hypotheses.']),
            6: ('A smaller failing index would contradict the chosen counterexample’s minimality.', ['All earlier cases are true because the entire theorem is assumed.', 'Every smaller index automatically satisfies every statement.']),
            7: ('No: index 1 is outside the stated domain and needs separate support.', ['Yes: every smaller integer is always included.', 'Yes: every induction includes the case 1.']),
            8: ('No: the hypothesis covers only smaller indices; P(n) is the target.', ['Yes: strong induction includes the target itself.', 'Yes: any previously written formula may be assumed.']),
            9: ('Both earlier indices must be within the domain and below the target; enough bases must cover the startup.', ['Only n-1 must be in the domain.', 'Negative indices are automatically covered because they are smaller.']),
            10: ('At the first index there are no earlier assumptions, so the base must still be proved directly.', ['An empty earlier collection proves the base automatically.', 'The first case can use itself as a hypothesis.']),
            12: ('Each factor multiplies an integer greater than 1 to give n, so each lies strictly between 1 and n.', ['Every factor of n is strictly below n, including n itself.', 'Smaller factors are automatically prime.']),
            13: ('1 is outside the domain, and n is not smaller than the target.', ['Both factors are smaller than n.', 'The factorization fails because 1 times n is not n.']),
            14: ('No: constructing a prime product proves existence; comparing all products requires a separate argument.', ['Yes: any constructed representation must be unique.', 'Yes: all composite integers have exactly two prime factors.']),
            16: ('Every nonempty product of primes exceeds 1; allowing the empty product changes the convention.', ['1 is prime and already a one-factor product.', 'The empty product equals zero.']),
            20: ('Show that two distinct sets of exponents cannot produce the same integer.', ['Nothing remains: any construction is automatically unique.', 'Only one more example must be checked.']),
            23: ('Only amounts congruent to 18 modulo 4 are reached; the other residue classes need bases.', ['All amounts at least 18 are reached by adding 4.', 'Only multiples of 7 are reached.']),
            29: ('No: every obtainable amount is divisible by 3, but arbitrarily large amounts are not.', ['Yes: two stamp values always generate all sufficiently large integers.', 'No: only finitely many stamps are available.']),
            40: ('The negative coefficient needs a lower bound on the subtracted term, or its exact value.', ['An upper bound remains an upper bound after negation.', 'The negative term can always be omitted without changing equality.']),
            44: ('Every finite halving leaves a positive real; decrease need not reach zero.', ['Every decreasing real sequence reaches zero in finitely many steps.', 'Halving a positive number increases it.']),
            49: ('The specification permits every nonempty smaller split, including unequal lengths.', ['Equal halves cover every legal split.', 'Odd lengths cannot be valid inputs.']),
            50: ('No: the recursive call has the same measure and repeats without reaching a base.', ['Yes: every recursive call is smaller simply because it occurs later.', 'Yes: the return statement guarantees a return is reached.']),
            52: ('The recursive counts cover only later splits; the first split contributes one more.', ['The first split is already counted in both recursive pieces.', 'The first split is free because it creates the pieces.']),
            61: ('The invoked amount is 15, outside the range; check 18 through 21 and start the step at 22.', ['15 is covered because it is smaller than 19.', 'Checking 18 alone covers all later amounts by adding 4.']),
            62: ('Index 0 is outside the bound’s domain; check 1 and 2, then start the general step at 3.', ['Index 0 is covered because the sequence itself is defined there.', 'The bound needs no base at 2.']),
            63: ('It assumes the target; the strong hypothesis must stop below n.', ['It is valid because strong induction includes n.', 'It must assume every larger integer instead.']),
            64: ('The first index has no earlier cases to use and must still be proved.', ['All earlier cases imply the base without checking it.', 'A recursive definition proves every possible base claim.']),
            65: ('The decreasing measure must be well founded, such as a nonnegative integer.', ['Any strictly decreasing positive real measure suffices.', 'Only an upper bound on the measure is needed.']),
            66: ('Smaller factors are products of primes by the hypothesis, not necessarily primes themselves.', ['Every smaller positive integer is prime.', 'Only prime factors can be smaller than a composite.']),
            67: ('A nonempty set of negative reals need not have a least element.', ['Every nonempty real set has a least element.', 'The least negative real is minus one.']),
            69: ('Use a lower bound before multiplying by a negative coefficient, or use an exact formula.', ['Keep the inequality direction after every multiplication.', 'Replace the negative coefficient with its absolute value.']),
            70: ('Prove the calls decrease a well-founded measure and reach covered bases; conditional correctness does not ensure return.', ['A correct return value guarantees the algorithm returns.', 'A recursive algorithm terminates whenever its code is finite.']),
        },
    }
    for lesson, items in choices.items():
        for identifier, (correct, wrong) in items.items():
            recognition(f'{lesson}-{identifier}', correct, wrong)
