import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { comparableCatalog, comparableNotebook } from './mdx-metadata-parity.js';

const baseline = JSON.parse(
  await readFile('scripts/fixtures/declarative-runtime-baseline.json', 'utf8'),
) as { commit: string; artifacts: Record<string, string> };

const mdxBaseline = JSON.parse(
  await readFile('scripts/fixtures/mdx-metadata-baseline.json', 'utf8'),
);

for (const [artifact, originalExpected] of Object.entries(baseline.artifacts)) {
  test(`declarative migration preserves ${artifact} from ${baseline.commit}`, async () => {
    let expected = originalExpected;
    let bytes = await readFile('output/' + artifact);
    if (artifact === 'grading-catalog.json') {
      // Native Figure references are compared as semantic records; question data,
      // context prose, ordered definitions, and figure data remain exact. The
      // independently captured pre-migration fixture is never generated by tests.
      const catalog = JSON.parse(bytes.toString('utf8'));
      bytes = Buffer.from(JSON.stringify(comparableCatalog(catalog)));
      expected = mdxBaseline.catalogSemanticHash;
    }
    if (artifact === 'content/notebook.json') {
      bytes = Buffer.from(JSON.stringify(comparableNotebook(JSON.parse(bytes.toString('utf8')))));
      expected = mdxBaseline.notebookSemanticHash;
    }
    if (artifact === 'content/tex-teaching.json') {
      const typing = JSON.parse(bytes.toString('utf8'));
      for (const placement of typing.placements) delete placement.hash;
      bytes = Buffer.from(JSON.stringify(typing));
      expected = mdxBaseline.texTeachingSemanticHash;
    }
    assert.equal(
      createHash('sha256').update(bytes).digest('hex'),
      expected,
      'Unexpected curriculum/history change. Inspect the semantic diff; never refresh a migration baseline just to pass validation.',
    );
  });
}
